# Generated by Django 4.2 on 2024-04-12 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_facility_city_alter_city_name_alter_city_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_facility', to='admin_panel.facility'),
        ),
    ]
