# Generated by Django 4.2 on 2024-04-27 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_purposeofvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zone_city', to='admin_panel.city'),
        ),
    ]
