# Generated by Django 4.2 on 2024-04-11 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0003_facility_city_alter_city_name_alter_city_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='visitors_email')),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=13, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('purpose_of_visit', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=4096, upload_to='visitors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_company', to='admin_panel.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitor_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
