# Generated by Django 4.2 on 2024-04-11 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, verbose_name='visitors_email'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=13),
        ),
    ]
