# Generated by Django 4.2 on 2024-05-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms', '0003_alter_visitor_purpose_of_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='from_company',
            field=models.TextField(blank=True, null=True),
        ),
    ]
