# Generated by Django 4.2 on 2024-03-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customrole_remove_customuser_unique_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
    ]
