# Generated by Django 4.2 on 2024-04-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_company_id_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='company_id',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='email_address'),
        ),
    ]
