# Generated by Django 4.2 on 2024-04-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_company_id_customuser_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customrole',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
