# Generated by Django 4.2 on 2024-04-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_customuser_facility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='facility',
        ),
    ]
