# Generated by Django 4.2 on 2024-04-27 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_zone_city'),
        ('authentication', '0014_alter_customuser_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_zone', to='admin_panel.zone'),
        ),
    ]
